# Dataset
train_dir: /home/neelesh/research-project-security-sheriffs/code/Cats_Dogs/train
val_dir: /home/neelesh/research-project-security-sheriffs/code/Cats_Dogs/val
test_dir: /home/neelesh/research-project-security-sheriffs/code/Cats_Dogs/test

# Model
base: resnet
model: resnet34
# model: {model}
batch_size: 128
epochs: 100
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
lr_gamma: 0.1
optim_milestones: [20, 40, 80]
gpus: [0,1,2]

# Opt
num_workers: 16
pin_memory: True

# Debug
print_freq: 1
eval_freq: 5
checkpoints: Cats_Dogs/checkpoints/{model}
plots: Cats_Dogs/plots/{model}
resume: False
test_only: False

#For test only
model_path: /home/neelesh/research-project-security-sheriffs/code/Cats_Dogs/checkpoints/resnet34/model_100.pth
logfile: pgd_cats_dogs_resnet.txt